#!/bin/bash
# postinst script for astroberry64-server-hotspot

RED='\033[0;31m'
NC='\033[0m'

# Note: No need to disable wpa_supplicant - it doesn't exist in Raspberry Pi OS Trixie+
# NetworkManager is the default since Bookworm (Debian 12)

chmod 600 /etc/NetworkManager/system-connections/HotSpot.nmconnection
systemctl restart NetworkManager.service
